name: Updates

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - name: Update me on this event
        run: |
          curl "${{ secrets.GOTIFY_URL }}/message?token=${{ secrets.GOTIFY_TOKEN }}" -F "title=Script collection updated" -F "message=${{ github.event.head_commit.message }}" -F "priority=5"
